export const flags = {
    flag:[
        { "name": "Afghanistan", "flag": "https://flagcdn.com/w320/af.png" },
        { "name": "Albania", "flag": "https://flagcdn.com/w320/al.png" },
        { "name": "Algeria", "flag": "https://flagcdn.com/w320/dz.png" },
        { "name": "American Samoa", "flag": "https://flagcdn.com/w320/as.png" },
        { "name": "Angola", "flag": "https://flagcdn.com/w320/ao.png" },
        { "name": "Antigua and Barbuda", "flag": "https://flagcdn.com/w320/ag.png" },
        { "name": "Argentina", "flag": "https://flagcdn.com/w320/ar.png" },
        { "name": "Aruba", "flag": "https://flagcdn.com/w320/aw.png" },
        { "name": "Australia", "flag": "https://flagcdn.com/w320/au.png" },
        { "name": "Austria", "flag": "https://flagcdn.com/w320/at.png" },
        { "name": "Azerbaijan", "flag": "https://flagcdn.com/w320/az.png" },
        { "name": "Bahamas", "flag": "https://flagcdn.com/w320/bs.png" },
        { "name": "Bahrain", "flag": "https://flagcdn.com/w320/bh.png" },
        { "name": "Bangladesh", "flag": "https://flagcdn.com/w320/bd.png" },
        { "name": "Barbados", "flag": "https://flagcdn.com/w320/bb.png" },
        { "name": "Belarus", "flag": "https://flagcdn.com/w320/by.png" },
        { "name": "Belgium", "flag": "https://flagcdn.com/w320/be.png" },
        { "name": "Belize", "flag": "https://flagcdn.com/w320/bz.png" },
        { "name": "Benin", "flag": "https://flagcdn.com/w320/bj.png" },
        { "name": "Bermuda", "flag": "https://flagcdn.com/w320/bm.png" },
        { "name": "Bolivia", "flag": "https://flagcdn.com/w320/bo.png" },
        { "name": "Bosnia and Herzegovina", "flag": "https://flagcdn.com/w320/ba.png" },
        { "name": "Botswana", "flag": "https://flagcdn.com/w320/bw.png" },
        { "name": "Brazil", "flag": "https://flagcdn.com/w320/br.png" },
        { "name": "British Virgin Islands", "flag": "https://flagcdn.com/w320/vg.png" },
        { "name": "Brunei", "flag": "https://flagcdn.com/w320/bn.png" },
        { "name": "Bulgaria", "flag": "https://flagcdn.com/w320/bg.png" },
        { "name": "Cambodia", "flag": "https://flagcdn.com/w320/kh.png" },
        { "name": "Cameroon", "flag": "https://flagcdn.com/w320/cm.png" },
        { "name": "Canada", "flag": "https://flagcdn.com/w320/ca.png" },
        { "name": "Cape Verde", "flag": "https://flagcdn.com/w320/cv.png" },
        { "name": "Cayman Islands", "flag": "https://flagcdn.com/w320/ky.png" },
        { "name": "Chile", "flag": "https://flagcdn.com/w320/cl.png" },
        { "name": "China", "flag": "https://flagcdn.com/w320/cn.png" },
        { "name": "Christmas Island", "flag": "https://flagcdn.com/w320/cx.png" },
        { "name": "Colombia", "flag": "https://flagcdn.com/w320/co.png" },
        { "name": "Comoros", "flag": "https://flagcdn.com/w320/km.png" },
        { "name": "Cook Islands", "flag": "https://flagcdn.com/w320/ck.png" },
        { "name": "Costa Rica", "flag": "https://flagcdn.com/w320/cr.png" },
        { "name": "Croatia", "flag": "https://flagcdn.com/w320/hr.png" },
        { "name": "Cuba", "flag": "https://flagcdn.com/w320/cu.png" },
        { "name": "Curacao", "flag": "https://flagcdn.com/w320/cw.png" },
        { "name": "Cyprus", "flag": "https://flagcdn.com/w320/cy.png" },
        { "name": "Czech Republic", "flag": "https://flagcdn.com/w320/cz.png" },
        { "name": "Democratic Republic of the Congo", "flag": "https://flagcdn.com/w320/cd.png" },
        { "name": "Denmark", "flag": "https://flagcdn.com/w320/dk.png" },
        { "name": "Djibouti", "flag": "https://flagcdn.com/w320/dj.png" },
        { "name": "Dominica", "flag": "https://flagcdn.com/w320/dm.png" },
        { "name": "Dominican Republic", "flag": "https://flagcdn.com/w320/do.png" },
        { "name": "Ecuador", "flag": "https://flagcdn.com/w320/ec.png" },
        { "name": "Egypt", "flag": "https://flagcdn.com/w320/eg.png" },
        { "name": "El Salvador", "flag": "https://flagcdn.com/w320/sv.png" },
        { "name": "Equatorial Guinea", "flag": "https://flagcdn.com/w320/gq.png" },
        { "name": "Eritrea", "flag": "https://flagcdn.com/w320/er.png" },
        { "name": "Estonia", "flag": "https://flagcdn.com/w320/ee.png" },
        { "name": "Ethiopia", "flag": "https://flagcdn.com/w320/et.png" },
        { "name": "Falkland Islands", "flag": "https://flagcdn.com/w320/fk.png" },
        { "name": "Faroe Islands", "flag": "https://flagcdn.com/w320/fo.png" },
        { "name": "Fiji", "flag": "https://flagcdn.com/w320/fj.png" },
        { "name": "Finland", "flag": "https://flagcdn.com/w320/fi.png" },
        { "name": "France", "flag": "https://flagcdn.com/w320/fr.png" },
        { "name": "French Guiana", "flag": "https://flagcdn.com/w320/gf.png" },
        { "name": "French Polynesia", "flag": "https://flagcdn.com/w320/pf.png" },
        { "name": "Gabon", "flag": "https://flagcdn.com/w320/ga.png" },
        { "name": "Gambia", "flag": "https://flagcdn.com/w320/gm.png" },
        { "name": "Georgia", "flag": "https://flagcdn.com/w320/ge.png" },
        { "name": "Germany", "flag": "https://flagcdn.com/w320/de.png" },
        { "name": "Ghana", "flag": "https://flagcdn.com/w320/gh.png" },
        { "name": "Gibraltar", "flag": "https://flagcdn.com/w320/gi.png" },
        { "name": "Greece", "flag": "https://flagcdn.com/w320/gr.png" },
        { "name": "Greenland", "flag": "https://flagcdn.com/w320/gl.png" },
        { "name": "Grenada", "flag": "https://flagcdn.com/w320/gd.png" },
        { "name": "Guadeloupe", "flag": "https://flagcdn.com/w320/gp.png" },
        { "name": "Guam", "flag": "https://flagcdn.com/w320/gu.png" },
        { "name": "Guatemala", "flag": "https://flagcdn.com/w320/gt.png" },
        { "name": "Guinea", "flag": "https://flagcdn.com/w320/gn.png" },
        { "name": "Guinea-Bissau", "flag": "https://flagcdn.com/w320/gw.png" },
        { "name": "Guyana", "flag": "https://flagcdn.com/w320/gy.png" },
        { "name": "Haiti", "flag": "https://flagcdn.com/w320/ht.png" },
        { "name": "Honduras", "flag": "https://flagcdn.com/w320/hn.png" },
        { "name": "Hong Kong", "flag": "https://flagcdn.com/w320/hk.png" },
        { "name": "Hungary", "flag": "https://flagcdn.com/w320/hu.png" },
        { "name": "Iceland", "flag": "https://flagcdn.com/w320/is.png" },
        { "name": "India", "flag": "https://flagcdn.com/w320/in.png" },
        { "name": "Indonesia", "flag": "https://flagcdn.com/w320/id.png" },
        { "name": "Iran", "flag": "https://flagcdn.com/w320/ir.png" },
        { "name": "Iraq", "flag": "https://flagcdn.com/w320/iq.png" },
        { "name": "Ireland", "flag": "https://flagcdn.com/w320/ie.png" },
        { "name": "Isle of Man", "flag": "https://flagcdn.com/w320/im.png" },
        { "name": "Israel", "flag": "https://flagcdn.com/w320/il.png" },
        { "name": "Italy", "flag": "https://flagcdn.com/w320/it.png" },
        { "name": "Ivory Coast", "flag": "https://flagcdn.com/w320/ci.png" },
        { "name": "Jamaica", "flag": "https://flagcdn.com/w320/jm.png" },
        { "name": "Japan", "flag": "https://flagcdn.com/w320/jp.png" },
        { "name": "Jordan", "flag": "https://flagcdn.com/w320/jo.png" },
        { "name": "Kazakhstan", "flag": "https://flagcdn.com/w320/kz.png" },
        { "name": "Kenya", "flag": "https://flagcdn.com/w320/ke.png" },
        { "name": "Kiribati", "flag": "https://flagcdn.com/w320/ki.png" },
        { "name": "Kuwait", "flag": "https://flagcdn.com/w320/kw.png" },
        { "name": "Kyrgyzstan", "flag": "https://flagcdn.com/w320/kg.png" },
        { "name": "Latvia", "flag": "https://flagcdn.com/w320/lv.png" },
        { "name": "Lebanon", "flag": "https://flagcdn.com/w320/lb.png" },
        { "name": "Liberia", "flag": "https://flagcdn.com/w320/lr.png" },
        { "name": "Libya", "flag": "https://flagcdn.com/w320/ly.png" },
        { "name": "Lithuania", "flag": "https://flagcdn.com/w320/lt.png" },
        { "name": "Macao", "flag": "https://flagcdn.com/w320/mo.png" },
        { "name": "Macedonia", "flag": "https://flagcdn.com/w320/mk.png" },
        { "name": "Madagascar", "flag": "https://flagcdn.com/w320/mg.png" },
        { "name": "Malawi", "flag": "https://flagcdn.com/w320/mw.png" },
        { "name": "Malaysia", "flag": "https://flagcdn.com/w320/my.png" },
        { "name": "Maldives", "flag": "https://flagcdn.com/w320/mv.png" },
        { "name": "Mali", "flag": "https://flagcdn.com/w320/ml.png" },
        { "name": "Malta", "flag": "https://flagcdn.com/w320/mt.png" },
        { "name": "Marshall Islands", "flag": "https://flagcdn.com/w320/mh.png" },
        { "name": "Martinique", "flag": "https://flagcdn.com/w320/mq.png" },
        { "name": "Mauritania", "flag": "https://flagcdn.com/w320/mr.png" },
        { "name": "Mauritius", "flag": "https://flagcdn.com/w320/mu.png" },
        { "name": "Mayotte", "flag": "https://flagcdn.com/w320/yt.png" },
        { "name": "Mexico", "flag": "https://flagcdn.com/w320/mx.png" },
        { "name": "Micronesia", "flag": "https://flagcdn.com/w320/fm.png" },
        { "name": "Moldova", "flag": "https://flagcdn.com/w320/md.png" },
        { "name": "Monaco", "flag": "https://flagcdn.com/w320/mc.png" },
        { "name": "Montenegro", "flag": "https://flagcdn.com/w320/me.png" },
        { "name": "Montserrat", "flag": "https://flagcdn.com/w320/ms.png" },
        { "name": "Morocco", "flag": "https://flagcdn.com/w320/ma.png" },
        { "name": "Mozambique", "flag": "https://flagcdn.com/w320/mz.png" },
        { "name": "Myanmar", "flag": "https://flagcdn.com/w320/mm.png" },
        { "name": "Namibia", "flag": "https://flagcdn.com/w320/na.png" },
        { "name": "Nauru", "flag": "https://flagcdn.com/w320/nr.png" },
        { "name": "Netherlands", "flag": "https://flagcdn.com/w320/nl.png" },
        { "name": "Netherlands Antilles", "flag": "https://i.ibb.co/qYR19rgq/Flag-of-the-Netherlands-Antilles-1959-1986-svg.png" },
        { "name": "New Caledonia", "flag": "https://flagcdn.com/w320/nc.png" },
        { "name": "New Zealand", "flag": "https://flagcdn.com/w320/nz.png" },
        { "name": "Nicaragua", "flag": "https://flagcdn.com/w320/ni.png" },
        { "name": "Nigeria", "flag": "https://flagcdn.com/w320/ng.png" },
        { "name": "Niue", "flag": "https://flagcdn.com/w320/nu.png" },
        { "name": "Norfolk Island", "flag": "https://flagcdn.com/w320/nf.png" },
        { "name": "Northern Mariana Islands", "flag": "https://flagcdn.com/w320/mp.png" },
        { "name": "North Korea", "flag": "https://flagcdn.com/w320/kp.png" },
        { "name": "Norway", "flag": "https://flagcdn.com/w320/no.png" },
        { "name": "Oman", "flag": "https://flagcdn.com/w320/om.png" },
        { "name": "Pakistan", "flag": "https://flagcdn.com/w320/pk.png" },
        { "name": "Panama", "flag": "https://flagcdn.com/w320/pa.png" },
        { "name": "Papua New Guinea", "flag": "https://flagcdn.com/w320/pg.png" },
        { "name": "Paraguay", "flag": "https://flagcdn.com/w320/py.png" },
        { "name": "Peru", "flag": "https://flagcdn.com/w320/pe.png" },
        { "name": "Philippines", "flag": "https://flagcdn.com/w320/ph.png" },
        { "name": "Poland", "flag": "https://flagcdn.com/w320/pl.png" },
        { "name": "Portugal", "flag": "https://flagcdn.com/w320/pt.png" },
        { "name": "Puerto Rico", "flag": "https://flagcdn.com/w320/pr.png" },
        { "name": "Qatar", "flag": "https://flagcdn.com/w320/qa.png" },
        { "name": "Republic of the Congo", "flag": "https://flagcdn.com/w320/cg.png" },
        { "name": "Reunion", "flag": "https://flagcdn.com/w320/re.png" },
        { "name": "Romania", "flag": "https://flagcdn.com/w320/ro.png" },
        { "name": "Russia", "flag": "https://flagcdn.com/w320/ru.png" },
        { "name": "Saint Barthelemy", "flag": "https://flagcdn.com/w320/bl.png" },
        { "name": "Saint Helena", "flag": "https://flagcdn.com/w320/sh.png" },
        { "name": "Saint Kitts and Nevis", "flag": "https://flagcdn.com/w320/kn.png" },
        { "name": "Saint Lucia", "flag": "https://flagcdn.com/w320/lc.png" },
        { "name": "Saint Pierre and Miquelon", "flag": "https://flagcdn.com/w320/pm.png" },
        { "name": "Saint Vincent and the Grenadines", "flag": "https://flagcdn.com/w320/vc.png" },
        { "name": "Samoa", "flag": "https://flagcdn.com/w320/ws.png" },
        {"name": "Sao Tome and Principe", "flag": "https://flagcdn.com/w320/st.png"},
        {"name": "Saudi Arabia", "flag": "https://flagcdn.com/w320/sa.png"},
        {"name": "Senegal", "flag": "https://flagcdn.com/w320/sn.png"},
        {"name": "Serbia", "flag": "https://flagcdn.com/w320/rs.png"},
        {"name": "Seychelles", "flag": "https://flagcdn.com/w320/sc.png"},
        {"name": "Sierra Leone", "flag": "https://flagcdn.com/w320/sl.png"},
        {"name": "Singapore", "flag": "https://flagcdn.com/w320/sg.png"},
        {"name": "Sint Maarten", "flag": "https://flagcdn.com/w320/sx.png"},
        {"name": "Slovakia", "flag": "https://flagcdn.com/w320/sk.png"},
        {"name": "Slovenia", "flag": "https://flagcdn.com/w320/si.png"},
        {"name": "Solomon Islands", "flag": "https://flagcdn.com/w320/sb.png"},
        {"name": "Somalia", "flag": "https://flagcdn.com/w320/so.png"},
        {"name": "South Africa", "flag": "https://flagcdn.com/w320/za.png"},
        {"name": "South Korea", "flag": "https://flagcdn.com/w320/kr.png"},
        {"name": "Spain", "flag": "https://flagcdn.com/w320/es.png"},
        {"name": "Sri Lanka", "flag": "https://flagcdn.com/w320/lk.png"},
        {"name": "Sudan", "flag": "https://flagcdn.com/w320/sd.png"},
        {"name": "Suriname", "flag": "https://flagcdn.com/w320/sr.png"},
        {"name": "Sweden", "flag": "https://flagcdn.com/w320/se.png"},
        {"name": "Switzerland", "flag": "https://flagcdn.com/w320/ch.png"},
        {"name": "Syria", "flag": "https://flagcdn.com/w320/sy.png"},
        {"name": "Taiwan", "flag": "https://flagcdn.com/w320/tw.png"},
        {"name": "Tajikistan", "flag": "https://flagcdn.com/w320/tj.png"},
        {"name": "Tanzania", "flag": "https://flagcdn.com/w320/tz.png"},
        {"name": "Thailand", "flag": "https://flagcdn.com/w320/th.png"},
        {"name": "Togo", "flag": "https://flagcdn.com/w320/tg.png"},
        {"name": "Tonga", "flag": "https://flagcdn.com/w320/to.png"},
        {"name": "Trinidad and Tobago", "flag": "https://flagcdn.com/w320/tt.png"},
        {"name": "Tunisia", "flag": "https://flagcdn.com/w320/tn.png"},
        {"name": "Turkey", "flag": "https://flagcdn.com/w320/tr.png"},
        {"name": "Turkmenistan", "flag": "https://flagcdn.com/w320/tm.png"},
        {"name": "Ukraine", "flag": "https://flagcdn.com/w320/ua.png"},
        {"name": "United Arab Emirates", "flag": "https://flagcdn.com/w320/ae.png"},
        {"name": "United Kingdom", "flag": "https://flagcdn.com/w320/gb.png"},
        {"name": "United States", "flag": "https://flagcdn.com/w320/us.png"},
        {"name": "Uruguay", "flag": "https://flagcdn.com/w320/uy.png"},
        {"name": "Uzbekistan", "flag": "https://flagcdn.com/w320/uz.png"},
        {"name": "Vanuatu", "flag": "https://flagcdn.com/w320/vu.png"},
        {"name": "Venezuela", "flag": "https://flagcdn.com/w320/ve.png"},
        {"name": "Vietnam", "flag": "https://flagcdn.com/w320/vn.png"},
        {"name": "Yemen", "flag": "https://flagcdn.com/w320/ye.png"},
        {"name": "Zambia", "flag": "https://flagcdn.com/w320/zm.png"},
        {"name": "Zimbabwe", "flag": "https://flagcdn.com/w320/zw.png"}
      ]
      
}